version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/tomcat/webapps
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
  # AfterInstall:
  #   - location: change_own.sh
  #     timeout: 300
  #     runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root